version: '3.4'

services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    volumes:
      - /home/web/test-stand/work/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080
    network_mode: bridge